### ISSUE TITLE
Easier searching

### ISSUE THREAD

**Issue by mvexel** [mvexel/osmdiff#1]
It would be nice to be able to filter specific elements with an easier interface than 

`[n["new"] for n in a.modify if type(n["new"]) == Way and n["new"].tags.get("highway") == "residential"]`

List comprehensions are sweet things but not that sweet.

**Comment by themmes** [comment]
`filter(lambda n: type(n["new"]) == osm.Way and n["new"].tags.get("highway") == "residential", o.modify)`

Just an alternative, not saying its nicer or easier

**Comment by mvexel** [comment]
Uhm I created something of a duplicate of this #35 ..
