### ISSUE TITLE
<remark> should not always lead to an exception

### ISSUE THREAD

**Issue by LaurensJN** [mvexel/osmdiff#19]
In `augmenteddiff.py`, <remarks> are handled like:
https://github.com/mvexel/osmdiff/blob/facd3667f1cba6e41a00ef9a0ef7f5d358548811/src/osmdiff/augmenteddiff.py#L102-L103

While it is true that these remarks are errors, it's not always feasible to raise an exception and therefore not be able to parse the OSM features that do not contain an error. Is it possible to have an optional custom error handling? E.g. these remarks are only logged and no exception is raised

**Comment by mvexel** [comment]
I removed the exception and added a `remarks` list property to the AugmentedDiff class.
