### ISSUE TITLE
Timeout value in retrieve() function is removed

### ISSUE THREAD

**Issue by LaurensJN** [mvexel/osmdiff#22]
In issue #14  and MR #15, the timeout value in the function to retrieve AugmentedDiffs is set. 
Somewhere in the process this change is reverted, although I cannot exactly detect where it changed. Does this have a history, or should that be added again?

**Comment by edenh** [comment]
This issue was mentioned in a Magnet thread: http://localhost:3000/tuesday/project/clm6ik0rl0004rfww4szqyz6n?tab=thread%3Aclm6ipedu0006rfwwstyd7p71

**Comment by mvexel** [comment]
I put this back and will release 0.4 with it soon
