### ISSUE TITLE
AugmentedDiff and OSMChange grow over time for same sequence_number

### ISSUE THREAD

**Issue by themmes** [mvexel/osmdiff#8]
**Action**

```
[in]
o = AugmentedDiff()
o.frequency = "minute"
o.get_state()
%time o.retrieve()
o.sequence_number, o

[out]
CPU times: user 1.14 s, sys: 0 ns, total: 1.14 s
Wall time: 4.53 s

 (3254511, AugmentedDiff (18240 created, 2294 modified, 218 deleted))
```

wait... then

```
[in]
%time o.retrieve()
'Sequence', o.sequence_number, o

[out]
(3254511, AugmentedDiff (18841 created, 2524 modified, 242 deleted))
```

**Expected**

I expected the same data for both AugmentedDiff retrievals. However, the second retrieval one contained more data. Then I thought it would be because Overpass is still writing to the latest sequence. However, when reducing the `sequence_number` by 1 the same happens for "older" sequences.

**Question**

Am I misunderstanding how to use this library (is every sequence actively streaming?)? Or is this a bug?

**Comment by themmes** [comment]
I see, the `self.create` (and other actions) are not wiped on a `get_state()` nor with `retrieve()`

**Comment by mvexel** [comment]
Merged (finally :)) the PR, would you mind adding a note to the documentation mentioning this flag @themmes ?
